name = "EcomCopilot Connector"
handle = "ecomcopilot-connector"
client_id = "3b407c5dc62a8a04687707e38dc8cc23"
application_url = "https://shopify-saas-backend-zp36.onrender.com"
embedded = true

[auth]
redirect_urls = [
  "https://shopify-saas-backend-zp36.onrender.com/auth/shopify/callback"
]

[webhooks]
api_version = "2026-04"

[access_scopes]
scopes = "read_checkouts,read_orders,read_products"
optional_scopes = [ "read_customers" ]
use_legacy_install_flow = false
